baseURL: "http://yangchnet.github.io/Dessert"
title: Linote
paginate: 10
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: 存档
                  url: archives/
                  weight: 5
                - name: 搜索
                  url: search/
                  weight: 10
                - name: 标签
                  url: tags/
                  weight: 10
                - name: 分类
                  url: categories/
                  weight: 10

outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production # to enable google analytics, opengraph, twitter-cards and schema.
    author: 李昌

    defaultTheme: auto
    ShowShareButtons: true
    ShowReadingTime: true
    displayFullLangName: true
    ShowPostNavLinks: true
    ShowBreadCrumbs: true
    ShowToc: true
    # comments: false
    images: ["papermod-cover.png"]


    homeInfoParams:
            Title: "李昌的博客"
             
                      
    socialIcons:
        - name: github
          url: "https://github.com/yangchnet"

    assets:
            favicon: "https://raw.githubusercontent.com/lich-Img/blogImg/master/favicon.ico"
            favicon16x16: "https://raw.githubusercontent.com/lich-Img/blogImg/master/favicon.ico"
            favicon32x32: "https://raw.githubusercontent.com/lich-Img/blogImg/master/favicon32.ico"

    cover:
        hidden: true # hide everywhere but not in structured data
        hiddenInList: true # hide on list pages and home
        hiddenInSingle: true # hide on single page


taxonomies:
    category: categories
    tag: tags
    series: series

